Historique QCM
WildCodeSchool/orleans-0219-php-oryalis pull request #107
Opened 2019-07-02 09:13 UTC by Hyemi-w

2019-07-02 09:14 UTC, JessicaSalvat approved these changes
Ok

2019-07-02 10:17 UTC, sblondeau requested changes

2019-07-02 10:17 UTC, sblondeau commented on src/Controller/QuestionController.php
> +            $questions = $questionRepository->findAll(),
a revoir, tu as mis l'affectation dans ton tableau !!!

2019-07-02 10:17 UTC, sblondeau commented on src/DataFixtures/AnswerFixtures.php
> +            $answer->setQuestionId($this->getReference('question'. $faker->numberBetween($min = 0, $max = 11)));
setQuestion, pas setQuestionId

2019-07-02 21:05 UTC, sblondeau requested changes

2019-07-02 21:05 UTC, sblondeau commented on src/Controller/QuestionController.php
> +            'questions' => $questionRepository->findAll()
les trier par ordre de date ?

2019-07-02 21:11 UTC, sblondeau requested changes

2019-07-02 21:11 UTC, sblondeau commented on src/Controller/QuestionController.php
> +            'questions' => $questionRepository->findAll()
j'ai l'impression que c'est fait dans une PR suivante en fait... donc voit en corrigeant les conflits mais il faut que ce soit trié

2019-07-03 08:54 UTC, JessicaSalvat approved these changes
ok

2019-07-03 10:06 UTC, sblondeau approved these changes

2019-07-03 10:06 UTC, merged