Sprint5 us44 pdf
WildCodeSchool/orleans-0219-php-oryalis pull request #143
Opened 2019-07-04 16:37 UTC by dimxpas

2019-07-04 16:40 UTC, jiceR approved these changes

2019-07-04 21:14 UTC, sblondeau requested changes

2019-07-04 21:14 UTC, sblondeau commented on assets/scss/pdf.scss
> +/*.footer-expand-lg {
code commenté

2019-07-04 21:14 UTC, sblondeau commented on templates/formations/trainingPDF.html.twig
> +    <header>
pas de header du coup ? au moins pour mettre "Oryalis - formations" ou un truc du genre ? un logo serait top aussi

2019-07-04 23:52 UTC, dimxpas commented on assets/scss/pdf.scss
> +/*.footer-expand-lg {
ok

2019-07-05 16:04 UTC, dimxpas commented on templates/formations/trainingPDF.html.twig
> +    <header>
Je l'ai mis dans le footer

2019-07-05 16:04 UTC, jiceR approved these changes

2019-07-05 19:14 UTC, sblondeau approved these changes

2019-07-05 19:14 UTC, merged