Fix qcm
WildCodeSchool/orleans-0219-php-oryalis pull request #149
Opened 2019-07-05 11:59 UTC by dimxpas

Juste la vue admin, pas fonctionnelle, relations pas faites à faire plus tard dans un fix si possible

2019-07-05 12:06 UTC, jiceR approved these changes

2019-07-05 12:08 UTC, sblondeau requested changes

2019-07-05 12:08 UTC, sblondeau commented on templates/admin/question/edit.html.twig
> +{% extends 'layouAdmin.html.twig' %}
layout et pas layou

2019-07-08 12:10 UTC, sblondeau requested changes

2019-07-08 12:10 UTC, sblondeau commented on src/Controller/AnswerController.php
> +     * @Route("/", name="answer_index", methods={"GET"})
route et méthode inutile, à supprimer

2019-07-08 12:10 UTC, sblondeau commented on src/Controller/AnswerController.php
> +    public function show(Answer $answer): Response
idem, à supprimer

2019-07-08 12:10 UTC, sblondeau commented on templates/admin/answer/index.html.twig
> +    <h1>Answer index</h1>
à supprimer

2019-07-08 12:10 UTC, sblondeau commented on templates/admin/answer/show.html.twig
> +{% block title %}Answer{% endblock %}
à supprimer

2019-07-08 12:24 UTC, dimxpas commented on src/Controller/AnswerController.php
> +     * @Route("/", name="answer_index", methods={"GET"})
supprimer

2019-07-08 12:25 UTC, dimxpas commented on src/Controller/AnswerController.php
> +    public function show(Answer $answer): Response
supprimer

2019-07-08 12:26 UTC, dimxpas commented on templates/admin/answer/index.html.twig
> +    <h1>Answer index</h1>
supprimer

2019-07-08 12:26 UTC, dimxpas commented on templates/admin/answer/show.html.twig
> +{% block title %}Answer{% endblock %}
supprimer

2019-07-08 13:34 UTC, sblondeau approved these changes

2019-07-08 13:34 UTC, merged