Sprint01_US_03_Footer
WildCodeSchool/orleans-0219-php-oryalis pull request #15
Opened 2019-06-05 10:20 UTC by JessicaSalvat

2019-06-05 11:56 UTC, Hyemi-w commented on assets/scss/app.scss
> +@import "~bootswatch/dist/lux/bootswatch";
il y a deux fois l'appel de bootswatch et bootstrap, sûrement dû au merge avec dev :)

2019-06-05 11:56 UTC, Hyemi-w commented on templates/_Footer.html.twig
> +                <h5 class="font-weight-bold text-uppercase">Orialys</h5>
C'est Oryalis et non pas Orialys !

2019-06-05 11:56 UTC, Hyemi-w commented on templates/_Footer.html.twig
> +                    <p>
`<p>` tout seul ?

2019-06-05 11:56 UTC, Hyemi-w commented on templates/_Footer.html.twig
> +                    <p><a class="footer_link" href="">Nous contacter</a></p>
Je crois que c'est inutile de mettre un `<a>` dans un `<p>`

2019-06-05 11:56 UTC, Hyemi-w commented on templates/_Footer.html.twig
> +                    </li>
Fermeture de `</li>` tout seul ? je pense que tu t'es trompée avec le `<p>` au dessus :)

2019-06-05 13:46 UTC, Hyemi-w approved these changes

2019-06-05 15:37 UTC, sblondeau requested changes

2019-06-05 15:37 UTC, sblondeau commented on assets/scss/app.scss
> +            font-family: 'Font Awesome\ 5 Free';
les font doivent être en variable SCSS. Mais là votre font s'appelle "Font Awesome\ 5 Free" ? c'est bizarre comme nom :/

2019-06-05 15:37 UTC, sblondeau commented on assets/scss/app.scss
> +                font-family: Quicksand, sans-serif;
idem nom de police en variable

2019-06-05 15:37 UTC, sblondeau commented on templates/_Footer.html.twig
> +                <ul class="list-unstyled">
c'est pas top un `<ul><li>` avec des `<p>` pour afficher une adresse...
mieux vaut utiliser la baliser `<address>` avec des `<br/>`; je te laisse te renseigner sur le net si besoin

2019-06-05 15:37 UTC, sblondeau commented on templates/_Footer.html.twig
> +<!--Footer-->
le nom de fichier devrait etre _footer pas _Footer

2019-06-06 09:02 UTC, Hyemi-w approved these changes

2019-06-06 13:09 UTC, sblondeau requested changes

2019-06-06 13:09 UTC, sblondeau commented on assets/scss/_vars.scss
> +$quicksand : "Quicksand", sans-serif;
Non ! le nommage c'est comme pour la couleur.
C'est $mainFont ou $titleFont ou autre, mais pas le nom de la police sinon ça ne sert à rien ;-)

2019-06-06 13:44 UTC, JessicaSalvat commented on assets/scss/_vars.scss
> +$quicksand : "Quicksand", sans-serif;
Oups !

2019-06-07 07:57 UTC, sblondeau approved these changes

2019-06-07 07:58 UTC, merged