homepage section presentation
WildCodeSchool/orleans-0219-php-oryalis pull request #17
Opened 2019-06-05 14:43 UTC by jiceR

2019-06-05 14:47 UTC, JessicaSalvat approved these changes
Ok

2019-06-06 13:12 UTC, sblondeau requested changes
Une partie n'est pas corrigé

2019-06-06 13:12 UTC, sblondeau commented on templates/home.html.twig
> +                    <h2 class="pb-4 text-center">Qui sommes-nous ?</h2>
un h1 plutot non ? à moins qu'il y en ait déjà un plus haut à venir ?

2019-06-06 13:12 UTC, sblondeau commented on templates/home.html.twig
> +        <div class="container ">
pourquoi une classe container dans un container-fluid? 
et il faudrait une balise <section> pour débuter la page au lieu d'un simple div

2019-06-06 14:44 UTC, JessicaSalvat approved these changes
Ok

2019-06-07 07:59 UTC, sblondeau approved these changes

2019-06-07 08:20 UTC, merged