Sprint1 us02 banniere
WildCodeSchool/orleans-0219-php-oryalis pull request #20
Opened 2019-06-06 14:33 UTC by dimxpas

2019-06-06 14:36 UTC, JessicaSalvat approved these changes
Ok

2019-06-07 08:00 UTC, sblondeau reviewed
réduire un peu la taille du jumbotronHome.png (passer en jpg ou webp par ex)

2019-06-07 08:08 UTC, sblondeau requested changes

2019-06-07 08:08 UTC, sblondeau commented on assets/scss/app.scss
> +  text-shadow: 0 0 .1rem grey;
couleur en variable

2019-06-07 08:08 UTC, sblondeau commented on assets/scss/app.scss
> +  text-shadow: 0 0 .1rem grey;
idem

2019-06-07 08:08 UTC, sblondeau commented on assets/scss/app.scss
> +  color: white;
idem

2019-06-07 08:08 UTC, sblondeau commented on assets/scss/app.scss
> +      font-family: Quicksand, sans-serif;
variable scss pour les font

2019-06-07 08:08 UTC, sblondeau commented on assets/scss/app.scss
> +    font-family: 'Font Awesome\ 5 Free';
variable scss pour les font

2019-06-07 09:28 UTC, JessicaSalvat approved these changes
Ok

2019-06-07 10:11 UTC, sblondeau approved these changes

2019-06-07 10:11 UTC, merged