US_07_page_acceuil_prestations
WildCodeSchool/orleans-0219-php-oryalis pull request #21
Opened 2019-06-06 15:36 UTC by jiceR

2019-06-06 15:37 UTC, JessicaSalvat approved these changes
Ok

2019-06-07 08:09 UTC, sblondeau requested changes

2019-06-07 08:09 UTC, sblondeau commented on assets/scss/app.scss
> +        border: 8px solid #ffffff;
couleur en variable

2019-06-07 09:12 UTC, JessicaSalvat approved these changes
ok

2019-06-07 10:12 UTC, sblondeau approved these changes

2019-06-07 10:34 UTC, merged