Sprint02 us34 admin formation
WildCodeSchool/orleans-0219-php-oryalis pull request #44
Opened 2019-06-12 14:22 UTC by JessicaSalvat

2019-06-12 14:52 UTC, Hyemi-w commented on src/DataFixtures/AppFixtures.php
> +        // $manager->persist($product);
code commenté

2019-06-12 14:52 UTC, Hyemi-w commented on src/Repository/FormationRepository.php
> +    */
code commenté aussi ici

2019-06-12 14:52 UTC, Hyemi-w commented on assets/scss/app.scss
> +th {
il peut y avoir d'autres th dans d'autres fichiers, c'est peut être plus judicieux de rajouter une classe

2019-06-12 14:52 UTC, Hyemi-w commented on templates/base.html.twig
> +>>>>>>> e9f293e8a88288d380be5eb82f829b563de9b706
??? sûrement une erreur lors d'un merge !

2019-06-12 15:01 UTC, Hyemi-w approved these changes
ok

2019-06-12 20:21 UTC, sblondeau requested changes

2019-06-12 20:21 UTC, sblondeau commented on src/Controller/HomeController.php
> +     * @Route("/formation", name="formation")
pb ici ? une annotation sans méthode liée en dessous ?

2019-06-13 07:33 UTC, Hyemi-w approved these changes
ok

2019-06-13 13:29 UTC, sblondeau requested changes

2019-06-13 13:29 UTC, sblondeau commented on src/Entity/Formation.php
> +class Formation
Formation en français, Training en anglais !

2019-06-13 13:29 UTC, sblondeau commented on src/Repository/FormationRepository.php
> +class FormationRepository extends ServiceEntityRepository
TrainingRepository

2019-06-13 13:49 UTC, JessicaSalvat commented on src/Repository/FormationRepository.php
> +class FormationRepository extends ServiceEntityRepository
Boulet !

2019-06-13 14:08 UTC, Hyemi-w approved these changes
ok

2019-06-13 15:06 UTC, sblondeau requested changes

2019-06-13 15:06 UTC, sblondeau commented on src/Repository/TrainingRepository.php
> +    // /**
code comment à enlever

2019-06-13 15:06 UTC, sblondeau commented on src/Controller/AdminController.php
> +use App\Repository\FormationRepository;
TrainingRepository

2019-06-13 15:06 UTC, sblondeau commented on src/Controller/HomeController.php
> +use App\Repository\FormationRepository;
TrainingRepository

2019-06-13 15:06 UTC, sblondeau commented on src/DataFixtures/TrainingFixtures.php
> +            $formation = new Training();
$training

2019-06-13 15:06 UTC, sblondeau commented on src/Controller/AdminController.php
> +        return $this->render('admin/formation.html.twig', [
admin/training.html.twig

2019-06-14 07:36 UTC, dimxpas commented on assets/scss/appAdmin.scss
> +/**Formation admin**/
Formation -> Training

2019-06-14 07:36 UTC, dimxpas commented on assets/scss/appAdmin.scss
> +.link-formation {
link-training

2019-06-14 07:36 UTC, dimxpas commented on templates/admin/training.html.twig
> +                    <td><a href="{{ training.id }}" class="link-formation"> {{ training.title }}</a></td>
link-training

2019-06-14 08:30 UTC, sblondeau approved these changes

2019-06-14 08:30 UTC, merged