ajout vue et edit d'une formation
WildCodeSchool/orleans-0219-php-oryalis pull request #54
Opened 2019-06-17 12:49 UTC by JessicaSalvat

2019-06-17 13:13 UTC, dimxpas requested changes

2019-06-17 13:13 UTC, dimxpas commented on templates/layoutAdmin.html.twig
> -{% block header %}<h1>Homepage Admin</h1>{% endblock %}
laisse le block header supprime juste le \<h1> à l'intérieur

2019-06-17 15:15 UTC, dimxpas approved these changes

2019-06-18 12:12 UTC, sblondeau requested changes

2019-06-18 12:12 UTC, sblondeau commented on assets/scss/appAdmin.scss
> +  color: whitesmoke;
couleur variable scss

2019-06-18 12:12 UTC, sblondeau commented on src/Controller/TrainingController.php
> +            'trainings' => $trainingRepository->findAll(),
trier les trainings par ordre alphab peut être ?

2019-06-18 12:12 UTC, sblondeau commented on src/Entity/Training.php
> +     * @ORM\Column(type="string", length=255)
manque tous les @assert pour les validations coté serveur

2019-06-18 12:12 UTC, sblondeau commented on src/Entity/Training.php
> +     * @ORM\Column(type="string", length=255)
revoir si certains type=string seraient pas plutot des type text

2019-06-18 12:12 UTC, sblondeau commented on templates/admin/training/show.html.twig
> +<div class="row justify-content-center">
cette page doit être dans une PR séparée pour le show

2019-06-19 08:57 UTC, dimxpas approved these changes

2019-06-19 09:15 UTC, sblondeau approved these changes

2019-06-19 12:35 UTC, dimxpas approved these changes

2019-06-19 12:46 UTC, merged