Admin Lister les News
WildCodeSchool/orleans-0219-php-oryalis pull request #68
Opened 2019-06-20 11:47 UTC by Hyemi-w

2019-06-20 12:02 UTC, dimxpas approved these changes

2019-06-20 13:58 UTC, sblondeau requested changes

2019-06-20 13:58 UTC, sblondeau commented on src/Controller/NewsController.php
> +            'news' => $newsRepository->findAll(),
trier par ordre chronologique decroissant non ?

2019-06-24 08:17 UTC, dimxpas approved these changes

2019-06-24 10:11 UTC, sblondeau requested changes

2019-06-24 10:11 UTC, sblondeau commented on src/Controller/NewsController.php
> +use App\Form\News1Type;
News1 ?

2019-06-24 10:11 UTC, sblondeau commented on src/Form/News1Type.php
> +class News1Type extends AbstractType
pourquoi News1 ? à renommer

2019-06-24 13:10 UTC, sblondeau approved these changes

2019-06-24 13:10 UTC, merged