contact page form
WildCodeSchool/orleans-0219-php-oryalis pull request #83
Opened 2019-06-24 09:14 UTC by jiceR

2019-06-24 09:39 UTC, Hyemi-w commented on templates/base.html.twig
> -
Tu es pas censé toucher aux parties qui concernent pas ta US fais attention ou Sylvain va te taper sur les doigts ;)

2019-06-24 09:47 UTC, Hyemi-w commented on src/Repository/ContactRepository.php
> +    */
code commenté à supprimer

2019-06-24 09:47 UTC, Hyemi-w commented on templates/contact/index.html.twig
> +{% block title %}Hello ContactController!{% endblock %}
A changer !

2019-06-24 13:23 UTC, Hyemi-w reviewed
Tu as oublié de mettre le lien pour la page dans la navbar aussi

2019-06-25 14:30 UTC, dimxpas approved these changes

2019-06-25 15:02 UTC, sblondeau requested changes

2019-06-25 15:02 UTC, sblondeau commented on src/Entity/Contact.php
> +     * @ORM\Column(type="integer")
pas un integer, car si tu rentre un 06XXXX il va te le convertir en 6XXXX, mais un type=string

2019-06-25 15:02 UTC, sblondeau commented on src/notification/ContactNotification.php
> +            ->setFrom('noreply@test.com')
les mails doivent être mis en param dans le env.local

2019-06-25 15:02 UTC, sblondeau commented on src/notification/ContactNotification.php
> +    public function notify(Contact $contact)
non, ça ne va pas. 
ce que tu fais là ressemble à un service, donc devrait se trouver dans src/Service/Mailer et premettre l'envoi générique de mail.

2019-06-25 15:02 UTC, sblondeau commented on templates/mail/mail.html.twig
> +<h1>Société : {{ contact.firm }}</h1>
ce fichier doit etre au format HTML, donc commencer par un doctype etc.
Le mieux est d'étendre un emailTemplate qui lui contiendra tout cela, et ça sera réutilisable si besoin d'envoyer des mail à un autre moment

2019-07-04 21:11 UTC, sblondeau requested changes
tu as supprimé .env.test et phpunit.dist, il fallait les laisser !

2019-07-04 21:11 UTC, sblondeau commented on src/Entity/Contact.php
> +    private $email;
manque tous les asserts sur cette entity. Par ex ici pour verif que tu as un mail.
par ailleurs, Contact c'est aussi une table en DB ? car sinon, aucun intéret de mettre des @ORM !

2019-07-04 21:11 UTC, sblondeau commented on src/notification/ContactNotification.php
> +            ->setFrom('noreply@test.com')
tu as encore les mails "en dur" et non ceux que tu récupères dans ton controleur

2019-07-04 21:11 UTC, sblondeau commented on templates/base.html.twig
> -
je devrais...

2019-07-04 21:11 UTC, sblondeau commented on templates/mailBase.html.twig
> +<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
les scripts js sont je pense, inutiles pour le mail

2019-07-04 21:51 UTC, jiceR commented on src/notification/ContactNotification.php
> +            ->setFrom('noreply@test.com')
oui j'ai arrangé ça sur le reset mais j'ai oublié de le faire ici :/

2019-07-04 21:57 UTC, jiceR commented on templates/mailBase.html.twig
> +<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
Je voulais générer une enveloppe avec des ailes qui "sousvolerait" le texte en s'adaptant à la vitesse de lecture du destinataire. Mais je n'ai malheureusement pas eu le temps ;)
Du coup maintenant les <scripts> ne servent a rien effectivement.

2019-07-04 22:01 UTC, jiceR commented on src/notification/ContactNotification.php
> +            ->setFrom('noreply@test.com')
Haaa... oui ! j'ai oublié de supprimer de namespace. il ne sert plus a rien en fait.

2019-07-04 22:03 UTC, jiceR commented on src/Entity/Contact.php
> +    private $email;
Dois-je mettre une assert regex sur le tel ?

2019-07-05 07:27 UTC, sblondeau commented on src/Entity/Contact.php
> +    private $email;
non

2019-07-05 07:28 UTC, sblondeau commented on templates/mailBase.html.twig
> +<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
tu ne peux pas faire de js dans un mail, c'est généralement bloqué

2019-07-05 07:29 UTC, sblondeau requested changes

2019-07-05 07:29 UTC, sblondeau commented on src/Entity/Contact.php
> +     * @Assert\String
ajoute plutot des NotBlank que des String

2019-07-05 12:09 UTC, sblondeau approved these changes

2019-07-05 12:09 UTC, merged