Sprint2 us31 ajouter membre
WildCodeSchool/orleans-0219-php-oryalis pull request #87
Opened 2019-06-24 15:51 UTC by dimxpas

2019-06-25 09:14 UTC, jiceR approved these changes

2019-06-25 10:26 UTC, sblondeau requested changes

2019-06-25 10:26 UTC, sblondeau commented on src/Form/EmployeeType.php
> +            ->add('title', TelType::class)
trompé de ligne non ?

2019-06-25 10:26 UTC, sblondeau commented on templates/admin_employee/index.html.twig
> +        <a href="{{ path('employee_new') }}" class="btn add">+ Ajouter un membre</a>
le "+" on le met plutot via un fontawesome

2019-06-25 10:26 UTC, sblondeau commented on src/Entity/Employee.php
> +     * @var File
manque tous les asserts (sur le file et sur tous les autres champs de l'entity)

2019-06-25 12:03 UTC, dimxpas commented on src/Form/EmployeeType.php
> +            ->add('title', TelType::class)
Modifié

2019-06-25 12:03 UTC, dimxpas commented on templates/admin_employee/index.html.twig
> +        <a href="{{ path('employee_new') }}" class="btn add">+ Ajouter un membre</a>
Je l'ai retiré finalement

2019-06-25 13:31 UTC, dimxpas commented on src/Entity/Employee.php
> +     * @var File
Fait

2019-06-25 14:35 UTC, jiceR approved these changes

2019-06-25 15:05 UTC, sblondeau requested changes
les images dans uploads ne doivent pas etre versionnées

2019-06-26 07:29 UTC, Hyemi-w approved these changes
ok

2019-06-26 08:36 UTC, sblondeau approved these changes

2019-06-26 10:07 UTC, merged