Sprint04 us 27 admin ajouter news
WildCodeSchool/orleans-0219-php-oryalis pull request #95
Opened 2019-07-01 13:03 UTC by Hyemi-w

2019-07-01 13:58 UTC, JessicaSalvat requested changes

2019-07-01 13:58 UTC, JessicaSalvat commented on src/Controller/NewsController.php
> +     * @Route("/ajouter-une-actualite", name="news_new", methods={"GET","POST"})
j'ai un doute sur le nom de la route avec les tirets ?

2019-07-01 14:28 UTC, JessicaSalvat approved these changes
Ok

2019-07-01 14:50 UTC, sblondeau requested changes

2019-07-01 14:50 UTC, sblondeau commented on src/Controller/NewsController.php
> +    public function new(Request $request, ObjectManager $manager): Response
plutot EntityManagerInterface $entityManager

2019-07-01 14:50 UTC, sblondeau commented on src/Controller/NewsController.php
> +                'years' => range(2019, 2069, 1)
c'est quoi l'utilité de fixé ce range? plutot que de ne rien mettre ?

2019-07-01 14:50 UTC, sblondeau commented on src/Controller/NewsController.php
> +//            return $this->redirectToRoute('news_show', ['id' => $news->getId()]);
code commenté

2019-07-01 14:50 UTC, sblondeau commented on src/Entity/News.php
> +     *     minMessage="Le titre doit contenir au moins 2 caractères",
utilise {limit} dans tes messages d'erreur, ça reprendra automatiquement la valeur settée dans  le min et le max respectivement, ça évite les incohérences quand tu changes la valeur sur l'un et oublie le message associé !

A faire partout où c'est nécessaire bien entendu

2019-07-02 08:03 UTC, sblondeau approved these changes

2019-07-02 08:03 UTC, merged